package:
  format-version: "1.0.0"
  name: "wireless_services"
  type: "api"
  status: "production"
  required: false
  version: "v2.0.0-E1"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.2"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.0"
    - name: "wireless_ble"
      type: "package"
      version: "v1.4.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.5.0"
    - name: "shd"
      type: "package"
      version: "v1.1.0"      

