package:
  format-version: "1.0.0"
  name: "wireless_system_services"
  type: "api"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.0"

